@echo off

echo Converting files to DOS (djgpp) format...

echo # generated by fixdjgpp.bat > makefile
echo MAKEFILE_INC = makefile.dj >> makefile
echo include makefile.all >> makefile

cd ..

utod .../*.c .../*.h .../makefile.* .../*.bat
utod .../*.cfg .../*.en .../*.es .../*.txt .../*.arg

cd src

echo Done!
