@echo off

echo Converting files to DOS (djgpp) format...

echo # generated by fixdjgpp.bat > makefile
echo MAKEFILE_INC = makefile.dj >> makefile
echo include makefile.all >> makefile

utod *.bat .../*.c .../*.h makefile.*
utod *.arg ../*.cfg .../*.txt ../*.txt

echo Done!
