@echo off

echo Converting files to Windows (MSVC) format...

echo # generated by fixmsvc.bat > makefile
echo MAKEFILE_INC = makefile.vc >> makefile
echo include makefile.all >> makefile

cd ..

utod .../*.bat .../*.c .../*.h .../makefile.*
utod .../*.arg .../*.cfg .../*.en .../*.es .../*.txt

cd src

echo Done!
