@echo off

echo Converting files to Windows (MSVC) format...

echo # generated by fixmsvc.bat > makefile
echo MAKEFILE_INC = makefile.vc >> makefile
echo include makefile.all >> makefile

cd ..

utod .../*.c .../*.h .../makefile.* .../*.bat
utod .../*.cfg .../*.en .../*.es .../*.txt .../*.arg

cd src

echo Done!
