@echo off

echo Converting files to Windows (Mingw32) format...

echo # generated by fixming.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

echo Done!
