#!/bin/sh

echo "Converting files to QNX format..."

echo "# generated by fixqnx.sh" > makefile
echo "MAKEFILE_INC = makefile.qnx" >> makefile
echo "include makefile.all" >> makefile

find .. -type f "(" \
   -name "*.bat" -o -name "*.c" -o -name "*.h" -o -name "makefile.*" -o \
   -name "*.arg" -o -name "*.cfg" -o -name "*.en" -o -name "*.es" \
   ")" \
   -exec textto -l {}

echo "Done!"

