#!/bin/sh

echo "Converting files to Unix format..."

echo "# generated by fixunix.sh" > makefile
echo "MAKEFILE_INC = makefile.uni" >> makefile
echo "include makefile.all" >> makefile

find . -type f "(" \
   -name "*.c" -o -name "*.h" -o -name "*.arg" -o -name "*.txt" -o -name "makefile.*" \
   ")" \
   -exec sh -c "echo {};
		mv {} _tmpfile;
		tr -d \\\r < _tmpfile > {};
		touch -r _tmpfile {}; 
		rm _tmpfile" \;

echo "Done!"
