@echo off

echo Converting files to DOS (Watcom) format...

echo # generated by fixwat.bat > makefile
echo MAKEFILE_INC = makefile.wat >> makefile
echo include makefile.all >> makefile

cd ..

utod .../*.c .../*.h .../makefile.* .../*.bat
utod .../*.cfg .../*.en .../*.es .../*.txt .../*.arg

cd src

echo Done!
