@echo off

echo Converting files to DOS (Watcom) format...

echo # generated by fixwat.bat > makefile
echo MAKEFILE_INC = makefile.wat >> makefile
echo include makefile.all >> makefile

cd ..

utod .../*.bat .../*.c .../*.h .../makefile.*
utod .../*.arg .../*.cfg .../*.en .../*.es

cd src

echo Done!
