# Copyright (C) 1999, 2000, 2001  David Capello

include makefile.lst
include $(MAKEFILE_INC)

.PHONY: default all msg clean distclean depend

default: msg $(TARGET_NAME)
	@echo Done!

all: default

msg:
	@echo Compiling Qtetris...

clean:
	-rm -fv $(CLEAN_FILES)

distclean: clean
	-rm -fv $(DISTCLEAN_FILES)

depend:
	gcc -MM -MG $(TARGET_SRC_FILES) > _depend.tmp
	sed -e "s/^\([a-zA-Z0-9_]*\.o:\)/obj\/\1/" _depend.tmp > makefile.dep
	rm _depend.tmp

-include makefile.dep
